Rasi_list = [
    "mesa",
    "vrsabha",
    "mithuna",
    "karka",
    "simha",
    "kanya",
    "tula",
    "vrscika",
    "dhanu",
    "makara",
    "kumbha",
    "mina",
]

Masa_list = [
    "vaisakha",
    "jyestha",
    "asadha",
    "sravana",
    "bhadrapada",
    "asvina",
    "kartika",
    "margasirsa",
    "pausa",
    "magha",
    "phalguna",
    "caitra",
]

Naksatra_list = [
    "asvini",
    "bharani",
    "krttika",
    "rohini",
    "mrgasirsa",
    "ardra",
    "punarvasu",
    "pusya",
    "aslesa",
    "magha",
    "purvaphalguni",
    "uttaraphalguni",
    "hasta",
    "citra",
    "svati",
    "visakha",
    "anuradha",
    "jyestha",
    "mula",
    "purvasada",
    "uttarasada",
    "sravana",
    "dhanistha",
    "satabhisa",
    "purvabhadra",
    "uttarabhadra",
    "revati",
]
system = ["amanta", "purnimata"]
ayanamsa = "citrapaksa"
section = [ "full", "first_half", "second_half", "first_third", "second_third", "third_third" ]